trigger:
  - main
  - feat/release-pipeline

pool:
  vmImage: ubuntu-latest

variables:
  - name: npm_config_cache
    value: $(Pipeline.Workspace)/.npm

stages:
  - stage: Build
    displayName: "Build frontend"
    jobs:
      - job: frontend
        displayName: "Build frontend"
        timeoutInMinutes: 10
        steps:
          - checkout: self

          - task: UseNode@1
            displayName: "Use Node.js 20"
            inputs:
              version: "20.x"
              checkLatest: true

          - script: |
              node --version
              npm --version
              npm install -g npm@10.8.2
              npm --version
            displayName: "Use npm 10.8.2"

          - task: Cache@2
            displayName: "Cache npm dependencies"
            inputs:
              key: 'npm | "$(Agent.OS)" | frontend/package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(npm_config_cache)

          - script: npm ci --cache $(npm_config_cache)
            displayName: "Install frontend dependencies"
            workingDirectory: frontend

          - script: npm run build
            displayName: "Build frontend"
            workingDirectory: frontend

          - publish: frontend/dist/frontend/browser
            artifact: frontend-build
            displayName: "Publish frontend build artifact"

  - stage: Release
    displayName: "Release Frontend"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: deploy_frontend
        displayName: "Deploy to Azure App Service"
        steps:
          - download: current
            artifact: frontend-build
            displayName: "Download frontend build artifact"

          - task: AzureWebApp@1
            displayName: "Deploy to Azure App Service"
            inputs:
              azureSubscription: 'AzureResourceManager'
              appType: 'webAppLinux'
              appName: 'tourplanner-frontend'
              package: '$(Pipeline.Workspace)/frontend-build'
              startUpCommand: 'pm2 serve /home/site/wwwroot --no-daemon --spa'
